In [1]:
import pandas as pd
import numpy as np
import os
os.chdir('c://users//administrator//desktop//MACHINE LEARNING//Projects')


In [2]:
cc = pd.read_csv('crx.data.txt',header =None)

cc.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

In [3]:
cc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
0     690 non-null object
1     690 non-null object
2     690 non-null float64
3     690 non-null object
4     690 non-null object
5     690 non-null object
6     690 non-null object
7     690 non-null float64
8     690 non-null object
9     690 non-null object
10    690 non-null int64
11    690 non-null object
12    690 non-null object
13    690 non-null object
14    690 non-null int64
15    690 non-null object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.3+ KB


In [4]:
for i in range(len(cc.columns)):
    cc.iloc[:,i]=cc.iloc[:,i].replace('?',np.nan)
                   

In [5]:
np.sum(cc.isna())

0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13    13
14     0
15     0
dtype: int64

In [6]:
for i in range(len(cc.columns)):
    try:
        cc.iloc[:,i] = pd.to_numeric(cc.iloc[:,i])
        cc.iloc[:,i].fillna(np.mean(cc.iloc[:,i]),inplace =True)                  ## mean imputation
    except:
        cc.iloc[:,i] = cc.iloc[:,i]
        cc.iloc[:,i].fillna(cc.iloc[:,i].value_counts().index[0],inplace =True)         ##most frequent occuring value

In [7]:
np.sum(cc.isna()),cc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
0     690 non-null object
1     690 non-null float64
2     690 non-null float64
3     690 non-null object
4     690 non-null object
5     690 non-null object
6     690 non-null object
7     690 non-null float64
8     690 non-null object
9     690 non-null object
10    690 non-null int64
11    690 non-null object
12    690 non-null object
13    690 non-null float64
14    690 non-null int64
15    690 non-null object
dtypes: float64(4), int64(2), object(10)
memory usage: 86.3+ KB


(0     0
 1     0
 2     0
 3     0
 4     0
 5     0
 6     0
 7     0
 8     0
 9     0
 10    0
 11    0
 12    0
 13    0
 14    0
 15    0
 dtype: int64, None)

In [8]:
cc.describe()

1           2           7          10           13  \
count  690.000000  690.000000  690.000000  690.00000   690.000000   
mean    31.568171    4.758725    2.223406    2.40000   184.014771   
std     11.853273    4.978163    3.346513    4.86294   172.159274   
min     13.750000    0.000000    0.000000    0.00000     0.000000   
25%     22.670000    1.000000    0.165000    0.00000    80.000000   
50%     28.625000    2.750000    1.000000    0.00000   160.000000   
75%     37.707500    7.207500    2.625000    3.00000   272.000000   
max     80.250000   28.000000   28.500000   67.00000  2000.000000   

                  14  
count     690.000000  
mean     1017.385507  
std      5210.102598  
min         0.000000  
25%         0.000000  
50%         5.000000  
75%       395.500000  
max    100000.000000

In [9]:
y = cc.iloc[:,1]>np.mean(cc.iloc[:,1])

In [10]:
from matplotlib import pyplot as plt

#plt.figure(figsize=(20,5))
#plt.subplot(1,2,1)
#plt.hist(y)

In [11]:
cc.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  202.0    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g   43.0  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  280.0  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  100.0    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  120.0    0  +

In [12]:
cc_dummies = pd.get_dummies(cc)

In [13]:
cc_dummies.head()

1      2     7  10     13   14  0_a  0_b  3_l  3_u  ...   8_t  9_f  \
0  30.83  0.000  1.25   1  202.0    0    0    1    0    1  ...     1    0   
1  58.67  4.460  3.04   6   43.0  560    1    0    0    1  ...     1    0   
2  24.50  0.500  1.50   0  280.0  824    1    0    0    1  ...     1    1   
3  27.83  1.540  3.75   5  100.0    3    0    1    0    1  ...     1    0   
4  20.17  5.625  1.71   0  120.0    0    0    1    0    1  ...     1    1   

   9_t  11_f  11_t  12_g  12_p  12_s  15_+  15_-  
0    1     1     0     1     0     0     1     0  
1    1     1     0     1     0     0     1     0  
2    0     1     0     1     0     0     1     0  
3    1     0     1     1     0     0     1     0  
4    0     1     0     0     0     1     1     0  

[5 rows x 48 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
cc_num = cc.apply(le.fit_transform)

In [15]:
cc_num.head()

0    1    2   3   4   5   6   7   8   9   10  11  12  13   14  15
0   1  156    0   1   0  12   7  30   1   1   1   0   0  69    0   0
1   0  329   93   1   0  10   3  65   1   1   6   0   0  11  119   0
2   0   89   16   1   0  10   3  36   1   0   0   0   0  97  140   0
3   1  125   46   1   0  12   7  73   1   1   5   1   0  31    3   0
4   1   43  109   1   0  12   7  41   1   0   0   0   2  37    0   0

In [16]:
cc_num.iloc[:,13].unique()

array([ 69,  11,  97,  31,  37, 116,  54,  23,  62,  15,  39,  91,   0,
       106, 128,  29,  68, 101,  47, 151,  56, 139, 159,   8,  85,  19,
       144, 104,  75, 150, 130,  84,  52, 163,  86, 155, 153, 135,  64,
       168, 141,  44,  28, 117,  98, 167,  66,  35,  58,  93,  55,  21,
        49,  60, 107,  74, 132,  95, 122, 131, 113,  70,  10,  63, 129,
       140,  27,  17, 127, 126,   3,   7,  32, 137, 119,   5,   2,  40,
       152,  67,  46, 123,  13,  14, 124,  48,  36,  16,  73,  81,  51,
         4,  80, 154,  88, 149,  76,  25,  20,  38, 147,  43,  42, 100,
        50,  94, 110,  33, 164, 142,  83,  57, 169, 133, 145, 111, 148,
       161, 121,  96,  77, 114,  45,  61, 160, 157, 170,  79,  72,  34,
       115,  12,  18,  26,  59,   1,  24, 143,  89,   6,  92, 109, 105,
        99, 120,  30,  87, 165, 158,  41, 156, 162,  53,  71, 125, 108,
       136, 166, 138,   9,  65, 102, 112,  78, 118,  22,  82, 103, 134,
       146,  90], dtype=int64)

In [17]:
cc_1 =cc_num.drop([10,13],axis = 1) 

In [18]:
x , y = cc_1.iloc[:,:-1] , cc_1.iloc[:,-1]    ## data and target

In [29]:
y.value_counts()                #BALENCED CLASS

1    383
0    307
Name: 15, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split as tts

In [21]:
x_tr,x_ts,y_tr,y_ts = tts(x,y ,test_size = 0.2,random_state =2)

In [23]:
from sklearn.linear_model import LogisticRegression

lr =LogisticRegression()

In [24]:
model = lr.fit(x_tr,y_tr)

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [26]:
model.score(x_tr,y_tr),model.score(x_ts,y_ts)

(0.8677536231884058, 0.8623188405797102)

In [30]:
from sklearn.metrics import classification_report as cr ,accuracy_score as acs,f1_score as f1,confusion_matrix as cm

In [31]:
y_tsp =model.predict(x_ts)

In [32]:
acs(y_ts,y_tsp)

0.8623188405797102

In [33]:
f1(y_ts,y_tsp)

0.8613138686131387

In [34]:
cm(y_ts,y_tsp)

array([[60,  8],
       [11, 59]], dtype=int64)

In [36]:
print(cr(y_ts,y_tsp))

              precision    recall  f1-score   support

           0       0.85      0.88      0.86        68
           1       0.88      0.84      0.86        70

   micro avg       0.86      0.86      0.86       138
   macro avg       0.86      0.86      0.86       138
weighted avg       0.86      0.86      0.86       138



In [ ]:
## SCALING AND TRYING AGAIN

In [47]:
from sklearn.preprocessing import MinMaxScaler

In [48]:
mms = MinMaxScaler(copy=True, feature_range=(0, 1))

In [49]:
scaler = mms.fit(cc_1)

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [50]:
cc_2 = scaler.transform(cc_1)

In [54]:
cc_2 =pd.DataFrame(cc_2)


In [55]:
cc_2.head()

0         1         2    3    4         5      6         7    8    9   \
0  1.0  0.446991  0.000000  0.5  0.0  0.923077  0.875  0.229008  1.0  1.0   
1  0.0  0.942693  0.434579  0.5  0.0  0.769231  0.375  0.496183  1.0  1.0   
2  0.0  0.255014  0.074766  0.5  0.0  0.769231  0.375  0.274809  1.0  0.0   
3  1.0  0.358166  0.214953  0.5  0.0  0.923077  0.875  0.557252  1.0  1.0   
4  1.0  0.123209  0.509346  0.5  0.0  0.923077  0.875  0.312977  1.0  0.0   

    10   11        12   13  
0  0.0  0.0  0.000000  0.0  
1  0.0  0.0  0.497908  0.0  
2  0.0  0.0  0.585774  0.0  
3  1.0  0.0  0.012552  0.0  
4  0.0  1.0  0.000000  0.0

In [56]:
x , y = cc_2.iloc[:,:-1] , cc_2.iloc[:,-1]

In [57]:
x_tr,x_ts,y_tr,y_ts = tts(x,y ,test_size = 0.2,random_state =2)

In [58]:
lr2 =LogisticRegression()

In [59]:
model2 = lr2.fit(x_tr,y_tr)

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [60]:
model.score(x_tr,y_tr),model.score(x_ts,y_ts)

(0.8514492753623188, 0.8695652173913043)

In [63]:
f1(y_ts,y_tsp)

0.8613138686131387

In [62]:
cm(y_ts,y_tsp)

array([[60,  8],
       [11, 59]], dtype=int64)

In [61]:
print(cr(y_ts,y_tsp))

              precision    recall  f1-score   support

         0.0       0.85      0.88      0.86        68
         1.0       0.88      0.84      0.86        70

   micro avg       0.86      0.86      0.86       138
   macro avg       0.86      0.86      0.86       138
weighted avg       0.86      0.86      0.86       138



In [ ]:
##IMPROVING THE PERFORMENCE WITH GRID SEARCH

In [65]:
from sklearn.model_selection import GridSearchCV as gscv

In [73]:
?gscv

In [ ]:
##KFOLD

In [70]:
from sklearn.model_selection import KFold

from sklearn.model_selection import cross_val_score as cvs

In [71]:
kfold = KFold(n_splits=5 , shuffle=True)

In [72]:
result = cvs(lr2 , x,y, cv = kfold,scoring='accuracy' )     ## cv is cross validation-- kfold ##
result.mean()

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs

0.8565217391304347

In [ ]:
from sklearn.model_selection import cross_val_score as cvs

scores = cvs(lr2,x,y,cv =10,scoring='accuracy')
